version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_IP}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_BASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chat2note_network

volumes:
  mysql_data:

networks:
  chat2note_network:
    driver: bridge